In [17]:
import numpy as np
import pandas as pd

In [18]:
df = pd.read_csv("/content/spam_ham_dataset.csv",index_col=0)
df.head()

     label                                               text  label_num
605    ham  Subject: enron methanol ; meter # : 988291\r\n...          0
2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...          0
3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...          0
4685  spam  Subject: photoshop , windows , office . cheap ...          1
2030   ham  Subject: re : indian springs\r\nthis deal is t...          0

In [19]:
df.drop("label_num",axis=1,inplace=True)
df.head()

     label                                               text
605    ham  Subject: enron methanol ; meter # : 988291\r\n...
2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...
3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...
4685  spam  Subject: photoshop , windows , office . cheap ...
2030   ham  Subject: re : indian springs\r\nthis deal is t...

In [20]:
df.reset_index(drop=True,inplace=True)

In [21]:
df.head()

  label                                               text
0   ham  Subject: enron methanol ; meter # : 988291\r\n...
1   ham  Subject: hpl nom for january 9 , 2001\r\n( see...
2   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...
3  spam  Subject: photoshop , windows , office . cheap ...
4   ham  Subject: re : indian springs\r\nthis deal is t...

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   5171 non-null   object
 1   text    5171 non-null   object
dtypes: object(2)
memory usage: 80.9+ KB

In [23]:
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
ps = PorterStemmer()
import re

In [24]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [25]:
corpus = []
for i in range(0,len(df["text"])):
    review = re.sub("[^a-zA-Z]"," ",df["text"][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words("english")]
    review = " ".join(review)
    corpus.append(review)

In [26]:
corpus

['subject enron methanol meter follow note gave monday preliminari flow data provid daren pleas overrid pop daili volum present zero reflect daili activ obtain ga control chang need asap econom purpos',
 'subject hpl nom januari see attach file hplnol xl hplnol xl',
 'subject neon retreat ho ho ho around wonder time year neon leader retreat time know time year extrem hectic tough think anyth past holiday life go past week decemb januari like think minut calend hand begin fall semest retreat schedul weekend januari youth minist confer brad dustin connect week go chang date follow weekend januari come part need think think agre import us get togeth time recharg batteri get far spring semest lot troubl difficult us get away without kid etc brad came potenti altern get togeth weekend let know prefer first option would retreat similar done past sever year year could go heartland countri inn www com outsid brenham nice place bedroom bedroom hous side side countri real relax also close brenham one hour minut golf shop antiqu craft store brenham eat dinner togeth ranch spend time meet saturday return sunday morn like done past second option would stay houston dinner togeth nice restaur dessert time visit recharg one home saturday even might easier trade would much time togeth let decid email back would prefer cours avail weekend democrat process prevail major vote rule let hear soon possibl prefer end weekend vote go way complain allow like tend great weekend great golf great fish great shop whatev make happi bobbi',
 'subject photoshop window offic cheap main trend abas darer prudent fortuit undergon lightheart charm orinoco taster railroad affluent pornograph cuvier irvin parkhous blameworthi chlorophyl robe diagrammat fogarti clear bayda inconvenienc manag repres smart hashish academi sharehold unload bad danielson pure caffein spaniard chargeabl levin',
 'subject indian spring deal book teco pvr revenu understand teco send us check receiv answer whether predermin price associ deal teco let us know give continu chase deal need',
 'subject ehronlin web address chang messag intend ehronlin user due recent chang ehronlin url aka web address access ehronlin need chang comput chang involv ad letter http refer url url access ehronlin http ehronlin enron com chang made ad url favorit browser',
 'subject spring save certif take save use custom appreci spring save certif foot locker ladi foot locker kid foot locker onlin store welcom custom appreci spring save certif use special certif receiv purchas either store onlin hurri day sale begin thursday march end sunday march share save today e mail offer friend mani item alreadi reduc discount taken lowest sale price click print custom appreci spring save certif must present coupon foot locker ladi foot locker kid foot locker store u foot locker canada particip program readi set save spring save discount automat appear use link type camlem promot code box checkout footlock com certif code camlem ladyfootlock com certif code camlem kidsfootlock com certif code camlem rememb return hassl free simpli bring item store nationwid mail left regist today learn new product promot event special simpli click term condit exclus appli pleas see manag complet detail certif must present time purchas cannot use conjunct discount offer associ benefit redeem cash applic tax must paid bearer cannot appli prior purchas gift card purchas void prohibit licens regul catalog exclus appli valid thursday sunday foot locker canada particip program wish receiv futur email pleas click unsubscrib',
 'subject look medic best sourc difficult make materi condit better best law easi enough ruin bad law excus found best simpliest site medic net perscript easi deliveri privat secur easi better see rightli pound week squint million got anyth ever want erect treatment pill anti depress pill weight loss http splice bombahakcx com knowledg human power synonym high qualiti stuff low rate moneyback guarante god natur sufficeth unto wise hath need author',
 'subject nom actual flow agre forward melissa jone texa util eileen ponton david avila lsp enserch us tu charli stone texa util tu melissa jone texa util tu hpl schedul enron com liz bellami enron com cc subject nom actual flow date nom flow mcf flow mmbtu btu',
 'subject nomin oct see attach file hplnl xl hplnl xl',
 'subject vocabl rnd word ascetic vcsc brand new stock attent vocalscap inc stock symbol vcsc vcsc top stock pick month april stock expect bounc cent level stock hit time low bounc back stock go explod next day watch soar watch stock go crazi next week break news vocalscap inc announc agreement resel mix network servic current price expect project specul price next day expect project specul price next day vocalscap network inc build compani revolution telecommun industri afford phone system hardwar onlin softwar rate canada us vocalscap compani global reach receiv intern attent develop voic ip voip applic solut includ award win eyefontm softphon real time pc phone advanc implement pbx system compani call center itsp servic provid vocalscap creat softwar interact solut revolv around global commun data voic converg compani use vocalscap voic internet protocol applic like ip pbx softswitch pc phone web phone provid real time human interact inform deliveri internet vocalscap solut busi offer qualiti voic servic anywher world rate significantli lower current long distanc charg develop softwar run voip network sell instal servic brand voip gateway gatekeep control softwar also licens softwar custom want brand voip solut vocalscap commit make great technolog challeng statu quo build st centuri compani chang way busi commun interact internet current price expect project specul price next day expect project specul price next day break news vocalscap inc announc agreement resel mix network servic katonah n prnewswir firstcal via comtex vocalscap inc pink vcsc emerg leader develop voic internet protocol voip telephoni solut announc today enter sale agent agreement mix network inc voip enhanc telephoni servic provid agreement provid vocalscap turnkey call card custom access mix network servic includ north american did phone number domest long distanc termin vocalscap also abl suppli client enhanc voip product includ pre paid call mix network north american network excit help compani launch voip busi model use solut whole pictur softwar network need rout call mix network give us abil offer wholesal monthli flat rate plan did client allow us build busi model like popular voip compani vonag packet say ryan gibson vp vocalscap network legal word continu inform within email contain forward look statement within mean section secur act section b secur exchang act statement express involv discuss respect predict goal expect belief plan project object assumpt futur event perform statement histor fact may forward look statement forward look statement base expect estim project time statement made involv number risk uncertainti could caus actual result event differ materi present anticip forward look statement action may identifi use word project forese expect estim believ understand part anticip statement indic certain action may could might occur inform provid within email pertain invest stock secur must understood inform provid invest advic emerg equiti alert advis reader subscrib seek advic regist profession secur repres decid trade stock featur within email none materi within report shall constru kind invest advic pleas mind interpret witer newslett news publish compani repres compani offici statement fact may differ real mean news releas meant say look news releas judg detail complianc section b disclos hold vcsc share prior public report awar inher conflict interest result hold due intent profit liquid share share may sold time even posit statement made regard compani sinc share inher conflict interest statement opinion reader public caution place undu relianc forward look statement base certain assumpt expect involv variou risk uncertainti could caus result differ materi set forth forward look statement pleas advis noth within email shall constitut solicit invit get posit sell secur mention herein newslett neither regist invest advisor affili broker dealer newslett paid third parti send report statement made express opinion treat may take posit sell secur mention time report includ forward look statement within mean privat secur litig reform act statement may includ term project specul price expect believ may soar move undervalu intend similar term',
 'subject report wffur attion brom est inst siupi pgst riw asent rest tont presyou tew con benco yee fater ust lyughtatum inenc sorepit grather aici graghteav allar oariti wow yur coon mer oit ithat yoit berst thar enth exciv',
 'subject enron hpl actual august teco tap enron hpl ga daili ls hpl lsk ic enron',
 'subject vic odin n ow bern hotbox carnal bride cutworm dyadic guardia continu born gremlin akin counterflow hereaft vocabularian pessimum yaound cannel bitch penetr demagogu arbitrari egregi adenosin rubin gil luminos delicti yarmulk sautern selfadjoint agleam exet picofarad consul dichotom boyhood balfour spheric frey pillori hoosier fibonacci cat hand',
 'subject tenaska iv juli darren pleas remov price tenaska iv sale deal juli enter demand fee amount thank megan',
 'subject underpr issu high return equiti stock report dont sieep stock hot one compani game transact inc stock symbol ggt currentiy trade rate strong purchas near term target long term target oo break news ggt game transact inc ggt ead provid onlin game porta manag pleas announc launch proprietari game portal k e n com furthermor compani begun intens market campaign support aunch establish eader onlin game industri k e n c oniin game destin peopl piay popular casino style game win real money foundat site onlin version keno game keno use ball number thru everi game hous draw bail random display number screen call keno board locat websit object game player guess number hous draw site shall also popuiar game near futur inciud bingo poker blackjack slot video game version tabi game patrick smyth ceo game transact inc remark game deveiop foresight creat user friendli experi without load time secur transact system deveiop multipi layer secur redund spent necessari time resourc test softwar ensur function secur consum focu group use deveiop process make sure player opul experi onlin futur market effort wi aim custom servic attent compani game transact inc deveiop provid onlin game servic onlin entertain game industri compani centra licens game portal k e n c destin oniin gambl properti player may particip number gambl oniin game fixtur foundat site cours onlin version keno game keno use bail number thru everi game hous draw ball random display number screen call keno board ocat websit object game piayer guess number hous draw site also popuiar game includ poker blackjack slot video game version tabi game game transact inc part oniin gambi industri said one fastest grow industri internet electron gambl report forecast revenu reach biliion market statist informa media grp giobal revenu oniin gambi wi reach bi ion biilion year accord report informa media grp say us wi gener percent onlin gambl revenu oo wherea europ wil gener percent north american oniin gambl revenu expect reach biliion year bi ion oo europ revenu wil grow billion year biilion oo oniin gambl revenu wi smailer asia pacif miliion year billion oo rest worid million year mi ion oo keno game one highest gross product mani north american govern bodi pubiic game corpor easi piay quick profitabi keno becom favorit gambier want excit lotteri draw without wait weekiy offer combin sophist hardwar softwar cut edg encrypt decrypt techniqu keno com deveiop icens system optima method onlin game inform within public contain futur look statement within mean section secur act section b secur exchang act statement express involv discuss respect predict expect belief pian project object goal assumpt futur event perform statement historica fact may futur look statement futur ook statement base expect estim project time statement made involv number risk uncertainti couid caus actual result event differ materia present anticip futur ook statement action may identifi use word project forese expect anticip estim believ understand statement indic certain action may could might occur futur ook statement base inform currentiy avaiiabi subject number risk uncertainti factor couid caus ggt actua resuit perform prospect opportun differ materialiy express impii futur ook statement mani microcap stock today compani additiona risk factor rais doubt abil continu go concern ggt report compani regist secur act henc imit public inform avaiiabl compani risk uncertainti factor includ without imit compani growth expect ongo fund requir specificaili compani growth prospect scalabl custom risk includ compani limit oper histori compani histori oper loss consum accept compani use licens technoiogi risk increas competit potentia need addit financ condit term financ consumm limit trade market compani secur possibi volatil compani stock price concentr ownership potentia fluctuat compani oper result publish report repres inform contain messag state ail materi fact omit materi fact necessari make statement therein misiead inform provid within report pertain invest stock secur must understood inform provid invest advic publish newslett advis reader subscrib seek advic regist profession secur repres decid trade stock featur within report none materia within report shall constru kind invest advic solicit mani compani verg bankruptci lose al money invest stock pubiish report regist invest expert subscrib view inform herein egal tax account invest advic refer past perform compani special seiect referenc base favorabi perform compani wouid need perfect time achiev resuit exampi given assur happen rememb alway past perform indic futur result thorough due dilig effort inciud review compani fii sec gov edgar onlin com avaiiabi shouid compiet prior invest al factua inform report gather pubiic sourc includ imit compani websit compani press releas pubiish disclos receipt fifteen thousand doilar third parti offic director affiiiat sharehold compani prepar oniin report awar inher confiict interest result compens due fact paid pubiic pubiish report beiiev inform reiiabl make assur accuraci compiet use materia within report constitut accept term wish stop futur maii feel wrongfuliy place membership pieas go send biank e mai thank subject stoxo yahoo com',
 'subject first deliveri wheeler oper vanc deal creat enter sitara bob vanc l taylor pm robert cotten hou ect ect cc juli meyer hou ect ect lisa hess hou ect ect cynthia hakemack hou ect ect susan smith hou ect ect donald p reinhardt hou ect ect melissa grave hou ect ect subject first deliveri wheeler oper bob follow product line ticket creat enter sitara base follow counterparti meter volum price period global wheeler oper mmbtu ga daili nya fyi creat submit commit reserv firm ticket remain term deal begin month march addit produc svc deal track im wellhead portfolio attach gather contract thank vlt x forward vanc l taylor hou ect pm esther buckley molli l carrier hou ect ect clem cernosek hou ect ect donna consemiu hou ect ect robert cook hou ect ect howard b camp hou ect ect lisa hess hou ect ect nathan l hlavati hou ect ect wayn e lightfoot hou ect jame mckay hou ect ect mari smith hou ect ect steve hpl schneider hou ect ect melissa grave hou ect ect michael walter hou ect ect jill zivley hou ect ect mari jo johnson hou ee ee rita wynn hou ect ect lauri allen hou ect ect cheryl jone gpgfin enron enron reid hansen gco enron enron darron c giron hou ect ect neal winfre hou ect ect susan smith hou ect ect gari bryan hou ect ect gari hank hou ect ect donald p reinhardt hou ect ect vanc l taylor hou ect ect david baumbach hou ect ect robert cotten hou ect ect brian riley hou ect ect jeff austin hou ee ee cynthia hakemack hou ect ect dawn c kenn hou ect ect lisa csiko hou ect ect j r fosdick gco enron enron carlo j rodriguez hou ect ect stephani gome hou ect ect pat clyne corp enron enron tom acton corp enron enron robert walker hou ect ect georg weissman hou ect ect joann harri na enron enron christi sweeney hou ect ect earl tisdal hou ect ect daren j farmer hou ect ect cc subject first deliveri wheeler oper pleas see attach letter',
 'subject swift may vol sean fyi check purchas swift tailgat meter make sure nom correct quantiti mari forward mari poorman na enron joan quick enron enronxg pm carlo j rodriguez hou ect ect mari poorman na enron enron jacki young hou ect ect cc brian riley hou ect ect mike morri corp enron enron subject swift may vol may first month nom king ranch plant mmbtu',
 'subject meter varianc ua clean daren vanc two meter new unallocat flow need purchas pleas respond deal number suggest resolut clear soon possibl mari enron katherin benedict ect pm mari poorman na enron enron fred boa hou ect ect aime lannou hou ect ect cc subject meter varianc ua clean hi guy pleas take look follow meter show varianc ua report varianc clear pleas send e mail pleas tri clear within next coupl day thank kathi benedict meter number varianc meter type daili swing product month august logist contact none volum mgmt contact anita luong meter number varianc meter type daili swing product month august logist contact none volum mgmt contact anita luong',
 'subject addit recruit happi introduc molli mage newest addit eop recruit team toni molli divid recruit duti along separ job function pleas review inform direct staf request either toni molli depend job need toni graham account risk confirm settlement posit open requir similar skill set candid pool molli mage logist global data manag research legal competit analysi contract administr posit open requir similar skill set candid pool thank assist hgm',
 'subject fw ercot load comparison origin messag gilbert smith doug sent tuesday may tmartin enron com subject ercot load comparison tom answer vi vi load growth hope help doug forward doug gilbert smith corp enron kevin cline enron enronxg pm doug gilbert smith corp enron enron cc eric saibi corp enron enron subject ercot load comparison pleas find attach spreadsheet compar hot day may may two tab one tab contain day may tab contain day may tab contain load data temp data particular day question day directli compar may thursday may thursday although two day preced may slightli warmer two day preced may peak mw higher peak mw similarli warm day peak would obvious even higher would put year year growth excess believ fall right line growth rate year year earlier analysi somewher rang let know question comment',
 'subject meter concord churchil one year rate one mm volum greater mm day price volum mm day less mm plu per month meter fee rate would cover transport competit ship channel market equistar channelview transport rate month term significantli differ mm volum greater mm day mm plu meter fee volum mm day less rate assum septemb start rate good friday august get em hot',
 'subject hpl nom januari see attach file hplnol xl hplnol xl',
 'subject tenaska iv receiv money spot sale tenaska iv octob except tenaska iv sale fee megan',

## Bag of Words BOW

In [34]:
# Create the Bag of Words Model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=100,binary=True)
X = cv.fit_transform(corpus).toarray()

In [35]:
X.shape

(5171, 100)

In [36]:
cv.vocabulary_

{'subject': np.int64(82),
 'enron': np.int64(25),
 'meter': np.int64(54),
 'follow': np.int64(30),
 'flow': np.int64(29),
 'provid': np.int64(69),
 'daren': np.int64(18),
 'pleas': np.int64(65),
 'daili': np.int64(17),
 'volum': np.int64(93),
 'ga': np.int64(33),
 'chang': np.int64(9),
 'need': np.int64(57),
 'hpl': np.int64(38),
 'nom': np.int64(59),
 'see': np.int64(76),
 'attach': np.int64(3),
 'file': np.int64(27),
 'xl': np.int64(99),
 'time': np.int64(89),
 'know': np.int64(43),
 'go': np.int64(35),
 'week': np.int64(95),
 'like': np.int64(46),
 'schedul': np.int64(75),
 'us': np.int64(91),
 'get': np.int64(34),
 'let': np.int64(45),
 'first': np.int64(28),
 'would': np.int64(97),
 'could': np.int64(15),
 'www': np.int64(98),
 'com': np.int64(10),
 'also': np.int64(2),
 'one': np.int64(62),
 'email': np.int64(23),
 'back': np.int64(5),
 'avail': np.int64(4),
 'make': np.int64(50),
 'manag': np.int64(51),
 'deal': np.int64(20),
 'send': np.int64(77),
 'receiv': np.int64(72),
 'price': np.int64(67),
 'messag': np.int64(53),
 'http': np.int64(39),
 'take': np.int64(84),
 'use': np.int64(92),
 'purchas': np.int64(70),
 'day': np.int64(19),
 'sale': np.int64(74),
 'today': np.int64(90),
 'mail': np.int64(49),
 'free': np.int64(32),
 'new': np.int64(58),
 'product': np.int64(68),
 'look': np.int64(48),
 'want': np.int64(94),
 'actual': np.int64(0),
 'forward': np.int64(31),
 'texa': np.int64(85),
 'cc': np.int64(8),
 'mmbtu': np.int64(55),
 'nomin': np.int64(60),
 'month': np.int64(56),
 'servic': np.int64(79),
 'current': np.int64(16),
 'compani': np.int64(11),
 'system': np.int64(83),
 'includ': np.int64(40),
 'call': np.int64(7),
 'inform': np.int64(41),
 'number': np.int64(61),
 'help': np.int64(36),
 'may': np.int64(52),
 'juli': np.int64(42),
 'thank': np.int64(87),
 'addit': np.int64(1),
 'sitara': np.int64(81),
 'bob': np.int64(6),
 'pm': np.int64(66),
 'robert': np.int64(73),
 'hou': np.int64(37),
 'ect': np.int64(21),
 'ticket': np.int64(88),
 'contract': np.int64(13),
 'corp': np.int64(14),
 'farmer': np.int64(26),
 'show': np.int64(80),
 'contact': np.int64(12),
 'origin': np.int64(63),
 'sent': np.int64(78),
 'question': np.int64(71),
 'per': np.int64(64),
 'energi': np.int64(24),
 'work': np.int64(96),
 'last': np.int64(44),
 'effect': np.int64(22),
 'th': np.int64(86),
 'list': np.int64(47)}

## N-Grams

In [37]:
# Create the Bag of Words Model  with n-grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=100,binary=True,ngram_range=(2,2))
X = cv.fit_transform(corpus).toarray()

In [38]:
cv.vocabulary_

{'subject enron': np.int64(82),
 'subject hpl': np.int64(84),
 'hpl nom': np.int64(47),
 'see attach': np.int64(80),
 'attach file': np.int64(2),
 'let know': np.int64(53),
 'enron com': np.int64(26),
 'pleas see': np.int64(72),
 'subject nom': np.int64(86),
 'melissa jone': np.int64(57),
 'charli stone': np.int64(6),
 'com cc': np.int64(9),
 'cc subject': np.int64(5),
 'next week': np.int64(62),
 'pleas advis': np.int64(66),
 'enron hpl': np.int64(28),
 'hpl actual': np.int64(44),
 'teco tap': np.int64(91),
 'tap enron': np.int64(89),
 'hpl ga': np.int64(45),
 'ga daili': np.int64(38),
 'ls hpl': np.int64(54),
 'tenaska iv': np.int64(92),
 'make sure': np.int64(55),
 'vanc taylor': np.int64(95),
 'pm robert': np.int64(74),
 'robert cotten': np.int64(78),
 'cotten hou': np.int64(11),
 'hou ect': np.int64(42),
 'ect ect': np.int64(17),
 'ect cc': np.int64(15),
 'juli meyer': np.int64(51),
 'meyer hou': np.int64(59),
 'susan smith': np.int64(88),
 'smith hou': np.int64(81),
 'ect melissa': np.int64(20),
 'melissa grave': np.int64(56),
 'grave hou': np.int64(41),
 'ect subject': np.int64(24),
 'meter volum': np.int64(58),
 'volum price': np.int64(96),
 'thank vlt': np.int64(93),
 'taylor hou': np.int64(90),
 'ect pm': np.int64(22),
 'ect robert': np.int64(23),
 'howard camp': np.int64(43),
 'ect mari': np.int64(19),
 'rita wynn': np.int64(77),
 'enron enron': np.int64(27),
 'gari hank': np.int64(40),
 'carlo rodriguez': np.int64(3),
 'ect pat': np.int64(21),
 'pat clyne': np.int64(65),
 'clyne corp': np.int64(8),
 'corp enron': np.int64(10),
 'tom acton': np.int64(94),
 'na enron': np.int64(60),
 'ect daren': np.int64(16),
 'daren farmer': np.int64(13),
 'farmer hou': np.int64(33),
 'enron subject': np.int64(31),
 'subject meter': np.int64(85),
 'subject fw': np.int64(83),
 'origin messag': np.int64(64),
 'enron cc': np.int64(25),
 'know question': np.int64(52),
 'natur ga': np.int64(61),
 'pleas note': np.int64(70),
 'hpl iferc': np.int64(46),
 'ami chokshi': np.int64(1),
 'ga nomin': np.int64(39),
 'http www': np.int64(50),
 'pleas repli': np.int64(71),
 'robert lloyd': np.int64(79),
 'enron pm': np.int64(30),
 'ect enron': np.int64(18),
 'enron north': np.int64(29),
 'north america': np.int64(63),
 'america corp': np.int64(0),
 'would like': np.int64(97),
 'forward ami': np.int64(36),
 'chokshi corp': np.int64(7),
 'pm daren': np.int64(73),
 'pleas let': np.int64(69),
 'pleas call': np.int64(67),
 'pleas contact': np.int64(68),
 'deal ticket': np.int64(14),
 'farmer daren': np.int64(32),
 'question thank': np.int64(76),
 'fuel cotton': np.int64(37),
 'cotton valley': np.int64(12),
 'subject revis': np.int64(87),
 'file hplno': np.int64(34),
 'hplno xl': np.int64(48),
 'xl hplno': np.int64(98),
 'question pleas': np.int64(75),
 'cc daren': np.int64(4),
 'file hplo': np.int64(35),
 'hplo xl': np.int64(49),
 'xl hplo': np.int64(99)}